language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: MaJU8qJGPzbQqniBhRZi2BSkRx1lZLicy2U1aV0JyN3jPf4xKEIaUs4YQYorH2ms4CiQ8uKs128p/Wz8rWjjjAEs0sqaWDYaUMFf1HI2JtBfUqeq6/X1hMwgipvC6JMmdfL7G3fOkbvRUZFL/SCfeqe3TzH/3JnjIo8pePhm6Nvc9p8UXodX4mT0wpmRpOZmszIEOIZoJJjHVgGXPmhiyI+6qFJMstIwFWD/HclQi+OozNCxt2SFEDy6rZ44QDWibkZtRZV4suJL70Nbhrv3YtrYWCB0wLyAx2Tc7UIgSIqQseYf3OzD5IAAT8tRZA6d60KJPOAxkrAt8e1O1BOcw5gw5j5yjN//eA3G8Gaqwp+FYUNInvMlUiqGK5uRDFXSi9H3sl14MuBto3KHfXA8I3/Fq1wuQFgXisUUtwxQb781s2iFIh6vMdQ+0m/5Bok1kO6LyHKMkosuCVBep9ZGpmuhdkS9vlQg967cD5ADmETrAIoV0yzkMqorl4LLnL47hUdLl/1ADVxWFALhE0QYcw2Vlq3Xgvg0SEQoppqm+x7ARCA4qUN6RZ0++LWiuxWLRtrX1DkMzXIkFI/FxtcKVgxlIt/11oGyMT7qiu2+KATBRglIEEEXanBgRbs5d9lbKvESLTHE4XiH3tStxxPReStWBvGgwuWQHMconZlaQbg=
  - secure: FhAlLe210Q6LBMrV/TIsJyzBrtxFzvHMIfOoaeN0OwOoQqldgpP/1H8B/HapxIF6VkPanqMqbbusyGrs9bHEKfWcdD4HctAm74jxC4kG1j/2bDdsJVtYRCQFdHhf3FOXmvEV4xcFgW37wHg0M123R8TfJJwlafCm34rU7Gb/LqsS3b8OElipjZKrql5Vd/ZqFYYcy2Wmj2lU/d92IzKohDR0hrkHAu+N6Jl3uoj/lBXNwUCnyNXB3aPHoq2Hb3GP6q/dp2R6239Y67SB/2uazHxpd0Hw8qmJSSXJFZorUD9A5Par1bx+7WKWhEqorDcXx2/Jij/Hts6S+SrDQ6/XsJ1mRh/svVUsQbnitl5ZTXlItw6BozQNPQ3mPzWzlyWSsaifD7h3+bhUgyR/qpSwDsIuqmpd1B04S5UgOfvhk0lKn+RQtlWsWGl1gW1aAgqKWd5Dzc2H1D7yuAU9Y8jiJs+JsrHCxc/YmDA7U8IabeTUxcG4A4To1uKh1lNL2fgSWMNs0V8ioj+02VoeZilB6EHbCJ/Ycxj+JZATtbYRoQX5hv8WuPjsT4gMew1MwqhqFZKH1vCDYcJoGyAuf0kXSNRJLuDHkF9nEWQASvyJ6Y4kQ+cqH6JURZ1fqWl7yZfE/6OZhbikuxFzWg5zraTKCN8wa5LmYUBGe5VbMR6TfK4=
